// ── UPGRADES ──────────────────────────────────────────────────────────────────
export const UPGRADES_CONFIG = {
  betterClick: {
    id: 'betterClick',
    name: 'Enhanced Click',
    description: '+0.5 credits per click per level',
    icon: '👆',
    baseCost: 10,
    maxLevel: 100,
    effect: (level) => `+${(level * 0.5).toFixed(1)} CPC`,
  },
  autoClicker: {
    id: 'autoClicker',
    name: 'Auto Clicker',
    description: '+1 credit/sec per level',
    icon: '🤖',
    baseCost: 50,
    maxLevel: 100,
    effect: (level) => `+${level} CPS`,
  },
  passiveIncome: {
    id: 'passiveIncome',
    name: 'Passive Income',
    description: '+0.5 credits/sec per level',
    icon: '💼',
    baseCost: 200,
    maxLevel: 100,
    effect: (level) => `+${(level * 0.5).toFixed(1)} CPS`,
  },
  comboMultiplier: {
    id: 'comboMultiplier',
    name: 'Combo Multiplier',
    description: '+20% click multiplier per level',
    icon: '⚡',
    baseCost: 500,
    maxLevel: 50,
    effect: (level) => `×${(1 + level * 0.2).toFixed(1)} clicks`,
  },
  criticalClick: {
    id: 'criticalClick',
    name: 'Critical Strike',
    description: '+5% crit chance (×10 credits) per level',
    icon: '💥',
    baseCost: 1000,
    maxLevel: 20,
    effect: (level) => `${level * 5}% crit`,
  },
  aiAssistant: {
    id: 'aiAssistant',
    name: 'AI Assistant',
    description: '+5 credits/sec per level',
    icon: '🧠',
    baseCost: 5000,
    maxLevel: 50,
    effect: (level) => `+${level * 5} CPS`,
  },
};

// ── SKINS ─────────────────────────────────────────────────────────────────────
export const SKINS = {
  default: {
    id: 'default',
    name: 'DUIKT Core',
    description: 'The classic cyberpunk interface',
    icon: '💎',
    unlockHint: 'Default skin',
    vars: {
      '--primary': '#00d4ff',
      '--primary-dark': '#0099bb',
      '--primary-glow': 'rgba(0, 212, 255, 0.3)',
      '--secondary': '#ff6b35',
      '--secondary-glow': 'rgba(255, 107, 53, 0.3)',
      '--accent': '#a855f7',
      '--accent-glow': 'rgba(168, 85, 247, 0.3)',
      '--bg': '#020b18',
      '--bg-card': '#061224',
      '--bg-card-alt': '#0a1e35',
      '--text': '#e2f4ff',
      '--text-muted': '#4a7a99',
      '--text-dim': '#2a4a66',
      '--success': '#22d47a',
      '--success-glow': 'rgba(34, 212, 122, 0.3)',
      '--danger': '#ff3a5c',
      '--danger-glow': 'rgba(255, 58, 92, 0.3)',
      '--warning': '#ffb800',
      '--warning-glow': 'rgba(255, 184, 0, 0.3)',
      '--border': '#0d2840',
      '--border-bright': '#1a4060',
      '--gold': '#ffd700',
      '--gold-glow': 'rgba(255, 215, 0, 0.3)',
      '--scan-line': 'rgba(0, 212, 255, 0.03)',
    },
  },
  neon: {
    id: 'neon',
    name: 'Neon Overdrive',
    description: 'Hypnotic magenta & cyan overload',
    icon: '🌈',
    unlockHint: 'Unlock by Prestiging once',
    vars: {
      '--primary': '#ff00cc',
      '--primary-dark': '#cc0099',
      '--primary-glow': 'rgba(255, 0, 204, 0.35)',
      '--secondary': '#00ffcc',
      '--secondary-glow': 'rgba(0, 255, 204, 0.3)',
      '--accent': '#ffff00',
      '--accent-glow': 'rgba(255, 255, 0, 0.3)',
      '--bg': '#07000f',
      '--bg-card': '#130020',
      '--bg-card-alt': '#1a003a',
      '--text': '#fff0ff',
      '--text-muted': '#7a4488',
      '--text-dim': '#3a1a4a',
      '--success': '#00ff99',
      '--success-glow': 'rgba(0, 255, 153, 0.3)',
      '--danger': '#ff0055',
      '--danger-glow': 'rgba(255, 0, 85, 0.3)',
      '--warning': '#ffee00',
      '--warning-glow': 'rgba(255, 238, 0, 0.3)',
      '--border': '#2a0040',
      '--border-bright': '#550088',
      '--gold': '#ffee00',
      '--gold-glow': 'rgba(255, 238, 0, 0.3)',
      '--scan-line': 'rgba(255, 0, 204, 0.04)',
    },
  },
  gold: {
    id: 'gold',
    name: 'Golden Empire',
    description: 'Luxury gold aesthetic for the elite',
    icon: '👑',
    unlockHint: 'Earn 1,000,000 total credits',
    vars: {
      '--primary': '#ffd700',
      '--primary-dark': '#c8a800',
      '--primary-glow': 'rgba(255, 215, 0, 0.35)',
      '--secondary': '#cd853f',
      '--secondary-glow': 'rgba(205, 133, 63, 0.3)',
      '--accent': '#ff8c00',
      '--accent-glow': 'rgba(255, 140, 0, 0.3)',
      '--bg': '#0e0800',
      '--bg-card': '#1a1000',
      '--bg-card-alt': '#251800',
      '--text': '#fff8dc',
      '--text-muted': '#8a7040',
      '--text-dim': '#4a3a10',
      '--success': '#9acd32',
      '--success-glow': 'rgba(154, 205, 50, 0.3)',
      '--danger': '#dc143c',
      '--danger-glow': 'rgba(220, 20, 60, 0.3)',
      '--warning': '#ff8c00',
      '--warning-glow': 'rgba(255, 140, 0, 0.3)',
      '--border': '#2a1a00',
      '--border-bright': '#4a3a00',
      '--gold': '#ffd700',
      '--gold-glow': 'rgba(255, 215, 0, 0.4)',
      '--scan-line': 'rgba(255, 215, 0, 0.02)',
    },
  },
  space: {
    id: 'space',
    name: 'Deep Space',
    description: 'Navigate the infinite dark cosmos',
    icon: '🚀',
    unlockHint: 'Click 10,000 times',
    vars: {
      '--primary': '#8b5cf6',
      '--primary-dark': '#6d28d9',
      '--primary-glow': 'rgba(139, 92, 246, 0.35)',
      '--secondary': '#0ea5e9',
      '--secondary-glow': 'rgba(14, 165, 233, 0.3)',
      '--accent': '#34d399',
      '--accent-glow': 'rgba(52, 211, 153, 0.3)',
      '--bg': '#010208',
      '--bg-card': '#05091a',
      '--bg-card-alt': '#080f28',
      '--text': '#c4b5fd',
      '--text-muted': '#4c3d7a',
      '--text-dim': '#1e1540',
      '--success': '#34d399',
      '--success-glow': 'rgba(52, 211, 153, 0.3)',
      '--danger': '#f87171',
      '--danger-glow': 'rgba(248, 113, 113, 0.3)',
      '--warning': '#fbbf24',
      '--warning-glow': 'rgba(251, 191, 36, 0.3)',
      '--border': '#0d1540',
      '--border-bright': '#1e2a6a',
      '--gold': '#fbbf24',
      '--gold-glow': 'rgba(251, 191, 36, 0.3)',
      '--scan-line': 'rgba(139, 92, 246, 0.03)',
    },
  },
  matrix: {
    id: 'matrix',
    name: 'Matrix Protocol',
    description: 'There is no spoon. Only credits.',
    icon: '🟩',
    unlockHint: 'Prestige 3 times',
    vars: {
      '--primary': '#00ff41',
      '--primary-dark': '#00cc33',
      '--primary-glow': 'rgba(0, 255, 65, 0.35)',
      '--secondary': '#00bb30',
      '--secondary-glow': 'rgba(0, 187, 48, 0.3)',
      '--accent': '#39ff14',
      '--accent-glow': 'rgba(57, 255, 20, 0.3)',
      '--bg': '#000500',
      '--bg-card': '#001a00',
      '--bg-card-alt': '#002200',
      '--text': '#00ff41',
      '--text-muted': '#007a20',
      '--text-dim': '#003a10',
      '--success': '#00ff41',
      '--success-glow': 'rgba(0, 255, 65, 0.3)',
      '--danger': '#ff0000',
      '--danger-glow': 'rgba(255, 0, 0, 0.3)',
      '--warning': '#ffff00',
      '--warning-glow': 'rgba(255, 255, 0, 0.3)',
      '--border': '#003300',
      '--border-bright': '#005500',
      '--gold': '#ffff00',
      '--gold-glow': 'rgba(255, 255, 0, 0.3)',
      '--scan-line': 'rgba(0, 255, 65, 0.05)',
    },
  },
};

// ── ACHIEVEMENTS ───────────────────────────────────────────────────────────────
export const ACHIEVEMENTS_CONFIG = [
  {
    id: 'first_click',
    name: 'First Contact',
    description: 'Click the button for the first time',
    icon: '👆',
    condition: (s) => s.totalClicks >= 1,
  },
  {
    id: 'click_100',
    name: 'Clicker Initiate',
    description: 'Click 100 times',
    icon: '✌️',
    condition: (s) => s.totalClicks >= 100,
  },
  {
    id: 'click_1000',
    name: 'Clicker Master',
    description: 'Click 1,000 times',
    icon: '🤙',
    condition: (s) => s.totalClicks >= 1000,
  },
  {
    id: 'click_10000',
    name: 'Clicker God',
    description: 'Click 10,000 times',
    icon: '🖐️',
    condition: (s) => s.totalClicks >= 10000,
  },
  {
    id: 'credits_1k',
    name: 'Kilo-Earner',
    description: 'Earn 1,000 total credits',
    icon: '💰',
    condition: (s) => s.totalCreditsEarned >= 1000,
  },
  {
    id: 'credits_100k',
    name: 'Six Figures',
    description: 'Earn 100,000 total credits',
    icon: '💎',
    condition: (s) => s.totalCreditsEarned >= 100000,
  },
  {
    id: 'credits_1m',
    name: 'Millionaire',
    description: 'Earn 1,000,000 total credits',
    icon: '🏆',
    condition: (s) => s.totalCreditsEarned >= 1000000,
  },
  {
    id: 'credits_1b',
    name: 'Billionaire',
    description: 'Earn 1,000,000,000 total credits',
    icon: '🌟',
    condition: (s) => s.totalCreditsEarned >= 1000000000,
  },
  {
    id: 'first_upgrade',
    name: 'Investor',
    description: 'Buy your first upgrade',
    icon: '📈',
    condition: (s) =>
      Object.values(s.upgrades).some((u) => u.level >= 1),
  },
  {
    id: 'upgrade_master',
    name: 'Upgrade Master',
    description: 'Reach level 10 on any upgrade',
    icon: '⚙️',
    condition: (s) =>
      Object.values(s.upgrades).some((u) => u.level >= 10),
  },
  {
    id: 'first_case',
    name: 'Case Opener',
    description: 'Open your first case',
    icon: '🎁',
    condition: (s) => s.casesOpened >= 1,
  },
  {
    id: 'case_10',
    name: 'Loot Addict',
    description: 'Open 10 cases',
    icon: '📦',
    condition: (s) => s.casesOpened >= 10,
  },
  {
    id: 'first_wheel',
    name: 'Fortune Seeker',
    description: 'Spin the Wheel of Fortune',
    icon: '🎡',
    condition: (s) => s.wheelSpins >= 1,
  },
  {
    id: 'wheel_5',
    name: 'Spinning Legend',
    description: 'Spin the wheel 5 times',
    icon: '🌀',
    condition: (s) => s.wheelSpins >= 5,
  },
  {
    id: 'first_prestige',
    name: 'Rebirth',
    description: 'Prestige for the first time',
    icon: '✨',
    condition: (s) => s.prestigeCount >= 1,
  },
  {
    id: 'prestige_3',
    name: 'Phoenix Rising',
    description: 'Prestige 3 times',
    icon: '🔥',
    condition: (s) => s.prestigeCount >= 3,
  },
  {
    id: 'prestige_10',
    name: 'Eternal Loop',
    description: 'Prestige 10 times',
    icon: '♾️',
    condition: (s) => s.prestigeCount >= 10,
  },
  {
    id: 'anti_survivor',
    name: 'Bug Survivor',
    description: 'Survive 5 anti-bonus attacks',
    icon: '🛡️',
    condition: (s) => s.antiBonusesSurvived >= 5,
  },
  {
    id: 'skin_collector',
    name: 'Skin Collector',
    description: 'Unlock 3 skins',
    icon: '🎨',
    condition: (s) => s.unlockedSkins.length >= 3,
  },
  {
    id: 'duiktcoin_rich',
    name: 'Duiktcoin Whale',
    description: 'Accumulate 100 Duiktcoins',
    icon: '🪙',
    condition: (s) => s.duiktcoins >= 100,
  },
];

// ── ANTI-BONUS CONFIG ──────────────────────────────────────────────────────────
export const ANTI_BONUS_CONFIG = {
  virus: {
    type: 'virus',
    name: 'VIRUS DETECTED',
    description: 'Click value reduced by 50%',
    icon: '🦠',
    duration: 20000,
    color: 'var(--danger)',
  },
  bug: {
    type: 'bug',
    name: 'SYSTEM BUG',
    description: 'Auto Clicker disabled',
    icon: '🐛',
    duration: 15000,
    color: 'var(--warning)',
  },
  ddos: {
    type: 'ddos',
    name: 'DDoS ATTACK',
    description: 'Clicking completely blocked',
    icon: '💀',
    duration: 10000,
    color: 'var(--danger)',
  },
  lag: {
    type: 'lag',
    name: 'SERVER LAG',
    description: 'Passive income reduced by 75%',
    icon: '🐌',
    duration: 25000,
    color: 'var(--warning)',
  },
};

// ── WHEEL SEGMENTS ─────────────────────────────────────────────────────────────
export const WHEEL_SEGMENTS = [
  { label: '500 CR',     type: 'credits',    amount: 500,      color: '#3b82f6' },
  { label: '2K CR',      type: 'credits',    amount: 2000,     color: '#22c55e' },
  { label: '2× Boost',   type: 'booster',    duration: 60000,  color: '#f97316' },
  { label: '100 CR',     type: 'credits',    amount: 100,      color: '#6b7280' },
  { label: '10K CR',     type: 'credits',    amount: 10000,    color: '#eab308' },
  { label: 'Nothing',    type: 'nothing',                      color: '#374151' },
  { label: '1 DUIKT',    type: 'duiktcoins', amount: 1,        color: '#8b5cf6' },
  { label: '50K CR',     type: 'credits',    amount: 50000,    color: '#ec4899' },
  { label: '3× Boost',   type: 'booster',    duration: 120000, color: '#ef4444' },
  { label: '1K CR',      type: 'credits',    amount: 1000,     color: '#14b8a6' },
  { label: '5 DUIKT',    type: 'duiktcoins', amount: 5,        color: '#f59e0b' },
  { label: 'Nothing',    type: 'nothing',                      color: '#4b5563' },
];

export const WHEEL_COOLDOWN = 5 * 60 * 1000; // 5 minutes
export const CASE_COST = 100;
export const FIX_ANTIBONU_COST = 500;
export const OFFLINE_EFFICIENCY = 0.5; // 50% of cps earned offline
